### ISSUE TITLE
Not working on Manjaro Linux

### ISSUE THREAD

**Issue by Nocrex** [Soundnode/soundnode-app#1131]
Version 0.6.5 just shows the interface but does not actually load any songs and does not react to mouse clicks (except the log out and settings button, although the options in that menu do not do anything)
After I looked around the Issues I tried version 7.0.0 and 7.0.1-RC1 but both of them do not even launch and give me an error saying `(Soundnode:27312): Pango-ERROR **: 10:09:55.031: Harfbuzz version too old (1.2.7)`
I am using Manjaro Linux 5.2.21

**Comment by jakejarrett** [comment]
Oh cheers, I'll take a look at the pango issue Friday or this weekend, might be worthwhile getting a working flatpak & snap version to reduce these issues in the future

**Comment by acxz** [comment]
On ArchLinux and still get the same issue with the latest release (7.0.0). Would be amazing for us, if you can publish a new release with the fix. Thank you!

**Comment by jakejarrett** [comment]
Fixed in `dev` branch, this was affecting me too now (and would have affected ubuntu in next release)

**Comment by acxz** [comment]
Can we not keep this issue open until a new tag is released with the fix? Considering end users are still facing this critical runtime error. If it was a smaller bug I understand, but as I stands right now we can't use the application, without a new release.

**Comment by jakejarrett** [comment]
yep. reopening because I was thinking this was another project my b

**Comment by acxz** [comment]
In the meanwhile for users on Arch Linux I have created a package for `soundnode-git` which tracks the latest git version of this repo. https://aur.archlinux.org/packages/soundnode-git/

**Comment by jakejarrett** [comment]
This is now in 7.0.1-RC2

**Comment by acxz** [comment]
Great!, but sadly Arch does not release RC.
